### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by yuant-gif** [JiJiJiang/ASV-Anti-Spoofing-DADA#2]
Hello, I haven't found the corresponding paper. Can you share it? Thank you very much!

**Comment by RicherMans** [comment]
Hey there, 
its 2 papers actually, both from INTERSPEECH.

Paper 1: 

https://speechlab.sjtu.edu.cn/~kyu/papers/2019/hjw77-wang-is2019-2.pdf

Paper 2:

http://www.interspeech2020.org/uploadfile/pdf/Mon-3-2-3.pdf

**Comment by yuant-gif** [comment]
> Hey there, its 2 papers actually, both from INTERSPEECH.
> 
> Paper 1:
> 
> https://speechlab.sjtu.edu.cn/~kyu/papers/2019/hjw77-wang-is2019-2.pdf
> 
> Paper 2:
> 
> http://www.interspeech2020.org/uploadfile/pdf/Mon-3-2-3.pdf

Thank you very much. I sincerely wish you all the best！
