### ISSUE TITLE
Updating path.sh

### ISSUE THREAD

**Issue by salihah-rilvan** [JiJiJiang/ASV-Anti-Spoofing-DADA#3]
May I ask how do I find my KALDI_ROOT to update path.sh? Is it meant to be a directory? Could you give an example if possible please?

**Comment by RicherMans** [comment]
Hey,
that's a standard environment variable of the [Kaldi](https://github.com/kaldi-asr/kaldi) toolkit.
You can see some example [here](https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/path.sh)

**Comment by JiJiJiang** [comment]
> May I ask how do I find my KALDI_ROOT to update path.sh? Is it meant to be a directory? Could you give an example if possible please?

Yes, exactly. KALDI_ROOT is the directory where you install the Kaldi toolkit. 

export KALDI_ROOT=/your/path/to/Kaldi

**Comment by salihah-rilvan** [comment]
Alright thanks! @RicherMans @JiJiJiang
