### ISSUE TITLE
Continue training

### ISSUE THREAD

**Issue by leonardltk** [JiJiJiang/ASV-Anti-Spoofing-DADA#6]
From the when calling `run.py train`, under the `main` function, are there parameters to pass such that they continue training where they left of instead of restart the training in a folder with a new timestamp ?

**Comment by JiJiJiang** [comment]
Hi, I guess you need to finetune your model or start training from a checkpoint. We have not implemented this in our code yet, but it is very easy to be implemented.

Firstly, find these lines in scripts/run.py in the main func.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/23723621/158843629-a2640e82-5cdb-42fb-aafa-e6eeaab811df.png">
Then, add a new line "model.load_state_dict(torch.load("/Your/path/to/model_XXX.th")['model'])" to initialize your model. BTW, be care of other training configs.
