### ISSUE TITLE
Elaboration of 'target-domain data is unlabeled in spoofing'

### ISSUE THREAD

**Issue by leonardltk** [JiJiJiang/ASV-Anti-Spoofing-DADA#8]
In your paper, under Section 2:
`
 Nevertheless, since the target-domain data is unlabeled in spoofing,
it is not easy to decide which domain discriminator is responsible for each target-domain training sample. 
`
Does it mean i can train the anti-spoofing model in this way:
1. Dataset A: bonafide, spoof
2. Dataset B: bonafide, spoof
3. Dataset C: only bonafide
 
and expect that during inference, the model can detect spoofing samples from Dataset C ?

**Comment by JiJiJiang** [comment]
Nope, in training, we have only two datasets:
1. Dataset A: source-domain, with spoofing label: bonafide/spoof
2. Dataset B: target-domain, without spoofing label.

We have two domain discriminator branches in the model: one for spoofing data and the other for bonafide data.
1. Source-domain: we have the spoofing label, so we know which domain discriminator should be trained.
2. Target-domain: we do not have the spoofing label, so we use the spoofing detector to predict whether it is spoofed or bonafide. During training, we can get its bonafide probability, and train both domain discriminators at the same time.

**Comment by leonardltk** [comment]
So dada cannot work for more than 2 different set of dataset distributions ?

**Comment by JiJiJiang** [comment]
Yes, if you regard one set as a domain...
